# 数据库操作
# 	创建数据库
CREATE DATABASE  db_01
CREATE DATABASE  db_02 CHARACTER SET utf8 COLLATE utf8_bin

# 	删除数据库
DROP DATABASE db_02

#	查看数据库
SHOW DATABASES
SHOW CREATE DATABASE db_02
CREATE DATABASE `CREATE`
DROP DATABASE `CREATE`