-- 日期与时间函数
SELECT CURRENT_DATE() FROM DUAL
SELECT CURRENT_TIME() FROM DUAL
SELECT CURRENT_TIMESTAMP() FROM DUAL

CREATE TABLE message(
	id INT,
	content VARCHAR(30),
	send_time DATETIME)

INSERT INTO message
	VALUES(1, 'AMS-XIY', CURRENT_TIMESTAMP())
INSERT INTO message
	VALUES(1, 'AMS-ZRH', NOW())
INSERT INTO message
	VALUES(1, 'AMS-PKX', NOW())
	
SELECT * FROM message

SELECT id, content, DATE(send_time) FROM message

-- 10分钟内的航班信息
SELECT * FROM message
	WHERE DATE_ADD(send_time,INTERVAL 10 MINUTE) >= NOW()
SELECT * FROM message
	WHERE DATE_SUB(NOW(),INTERVAL 10 MINUTE) <= send_time

SELECT DATEDIFF('2021-08-14', '1990-01-01') FROM DUAL

SELECT DATEDIFF(NOW(), '1997-11-23')/365 FROM DUAL

SELECT HOUR(NOW()) FROM DUAL

SELECT UNIX_TIMESTAMP() FROM DUAL
SELECT FROM_UNIXTIME(1628965872, '%Y-%m-%d %H:%i:%s') FROM DUAL