-- 数学计算函数
SELECT ABS(-8) FROM DUAL

SELECT BIN(8) FROM DUAL

SELECT CEILING(1.2) FROM DUAL
SELECT CEILING(-1.2) FROM DUAL

SELECT CONV(12,10,16) FROM DUAL
SELECT CONV('A',16,2) FROM DUAL

SELECT FLOOR(1.3) FROM DUAL
SELECT FLOOR(-1.3) FROM DUAL

SELECT FORMAT(78.123456789, 2) FROM DUAL

SELECT HEX(12) FROM DUAL

SELECT LEAST(1,3,-8) FROM DUAL

SELECT MOD(10,3) FROM DUAL

SELECT RAND() FROM DUAL